### ISSUE TITLE
Problem with eww config

### ISSUE THREAD

**Issue by THEGODFATHERRX** [obliviousofcraps/mf-dots#10]
Hi, eww says your ~/.config/eww/eww.yuck is missing? I think you were using eww 0.1 when you made the config, if you have already made a new config for eww 0.2, or have a config with the eww.yuck file, it would be really great if you can add that! thanks

**Comment by obliviousofcraps** [comment]
Yeah, sorry for the problem. But I haven't converted my old configs to the new configs so that's why its saying missing config. 

Also I don't have any plan to migrate to the new config as I am not really using eww right now at all. Sorry for the inconvenience but you're on your own.
