### ISSUE TITLE
[Bug] Eww widgets stay on top of windows

### ISSUE THREAD

**Issue by adamisafk** [obliviousofcraps/mf-dots#7]
With config identical to this repo, the widgets take priority over every window. Tried using the stacking and focusable tags but it doesn't change anything. Happens with or without a compositor.

![image](https://user-images.githubusercontent.com/22228197/126043655-9690d81b-2ef9-4274-bf5f-1887832fceae.png)

[There's an issue on the Eww repo](https://github.com/elkowar/eww/issues/192) with someone having the same problem, so maybe it's a problem with Eww itself.

**Comment by obliviousofcraps** [comment]
It indeed is a problem with eww. during the initial development the stacking="bg" attribute used to work and I used it a lot. but after the may or some update it stopped working.
